### ISSUE TITLE
Possibly include "Answers from 2017 Common Lisp experts"

### ISSUE THREAD

**Issue by phoe** [anticrisis/anticrisis.github.io#1]
Hey!

I made a compilation of responses to your blog post titled "Questions for 2017 Common Lisp experts". It's available at https://blog.teknik.io/phoe/p/365 with a mirror at https://gist.github.com/phoe/d93f968f22bbcc87070cdc5831762021

I thought you might want to include a link to the responses in your original blog post. If yes, then please do so; if not, then feel free to just close this issue.

~phoe

**Comment by anticrisis** [comment]
Thank you for doing this! I've updated the [post](https://anticrisis.github.io/2017/08/09/questions-for-2017-common-lisp-experts.html) to include links to your work.
